DROP TABLE IF EXISTS TBL_DEVICES;
  
CREATE TABLE TBL_DEVICE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  device_type VARCHAR(250) NOT NULL,
  name VARCHAR(250) NOT NULL,
  strength VARCHAR(250) DEFAULT NULL
);